
plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    id "com.google.devtools.ksp"
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file("keystore.properties")
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}


android {
    namespace = 'com.babsnet.accounting'
    compileSdk = 35

    defaultConfig {
        applicationId = "com.babsnet.accounting"
        minSdk = 23
        targetSdk = 35
        versionCode = 1
        versionName = "1.0"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }


    flavorDimensions "env"
    productFlavors {
        dev {
            dimension "env"
            applicationIdSuffix ".dev"
            versionNameSuffix "-dev"
            resValue "string", "app_name", "BaCs DEV"
            // buildConfigField "String", "BASE_URL", "\"https://dev.api.com\""
        }

        prod {
            dimension "env"
            resValue "string", "app_name", "BaCs"
            // buildConfigField "String", "BASE_URL", "\"https://api.com\""
        }
    }

    signingConfigs {
        release {
            if (keystorePropertiesFile.exists()) {
                storeFile rootProject.file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
            }
        }
    }

    buildTypes {
        debug {
            debuggable true
        }

        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        viewBinding true
    }

    java {
        toolchain {
            languageVersion.set(JavaLanguageVersion.of(17))
        }
    }
}

dependencies {
    // dependencies kamu biarkan seperti sekarang
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.androidx.constraintlayout

    implementation libs.material
    implementation libs.material.v1100

    implementation libs.androidx.lifecycle.livedata.ktx
    implementation libs.androidx.lifecycle.viewmodel.ktx

    implementation libs.androidx.navigation.fragment.ktx
    implementation libs.androidx.navigation.ui.ktx
    implementation libs.androidx.navigation.fragment.ktx.v260
    implementation libs.androidx.navigation.ui.ktx.v260

    implementation libs.androidx.drawerlayout
    implementation libs.google.material.v1100

    implementation libs.androidx.vectordrawable

    implementation libs.androidx.room.ktx
    implementation libs.androidx.room.runtime
    implementation libs.support.annotations
    implementation libs.androidx.annotation
    implementation libs.androidx.activity
    ksp libs.androidx.room.compiler

    implementation libs.itext7.core
    implementation libs.jxl

    implementation libs.androidx.viewpager2
    implementation libs.material.v130

    implementation libs.shimmer
    implementation libs.androidx.room.ktx.v252
    implementation(libs.core)

    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core
}
